### PR TITLE
Rename README.md to GauthamPrabhuMProjects.github.io

### PR DESCRIPTION
**Pull request by GauthamPrabhuM**

### CODE REVIEW

**Comment by niinpatel** [comment]
Can you make the changes on the forked repo. Thanks :)

**Comment by GauthamPrabhuM** [comment]
> Can you make the changes on the forked repo. Thanks :)

I am very sorry, I'm relatively new to github) and I messed up..by trying to change your repository.

**Comment by niinpatel** [comment]
> > Can you make the changes on the forked repo. Thanks :)
> 
> I am very sorry, I'm relatively new to github) and I messed up..by trying to change your repository.

No worries! I'm happy to see that you're using my project. Note, you may need to make some modification for different text as mentioned here https://github.com/niinpatel/happy-birthday-react-p5/blob/9d1e2fb0d7d26d0b8b858a793a917e6a322f69c4/src/App.js#L14-L15 and here https://github.com/niinpatel/happy-birthday-react-p5/blob/9d1e2fb0d7d26d0b8b858a793a917e6a322f69c4/src/sketch/sketch.js#L20-L28

**Comment by GauthamPrabhuM** [comment]
thank you so much..

**Pull request closed without merging**
